FROM node:10.11-alpine
RUN apk --no-cache add git python openssh-client make
RUN npm i -g nodemon
RUN mkdir -p ~/.ssh && (ssh-keyscan github.com >> ~/.ssh/known_hosts) && more ~/.ssh/known_hosts
WORKDIR /app
VOLUME /app/node_modules
CMD nodemon -w "package.json" -x "npm i && node app.js --watch"
