# lock to some node version
FROM node:12.13.1-alpine

# set env variables
ARG ENVIRONMENT=staging
ENV NODE_ENV=${ENVIRONMENT}

# copy project files
COPY . ./

# install NPM packages
RUN npm install --only=prod

# install NestJS CLI for build
RUN npm install -g @nestjs/cli

# build JS bundles
RUN npm run build

CMD ["node", "dist/main.js"]
